{
 "title": "Cumulus",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "query": "label_values(node_uname_info,nodename)  "
   }
  ]
 },
 "panels": [
  {
   "title": "Switch X received traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "mb/s " }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{ job=\"$hostname\"}[1m])*8/1000000"
    }
   ]
  },
  {
   "title": "Switch X Transmit traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "mb/s " }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{ job=\"$hostname\"}[1m])*8/1000000"
    }
   ]
  },
  {
   "title": "CPU Monitoring",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "percentage" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode=\"system\", job=\"$hostname\"}[1m])"
    }
   ]
  },
  {
   "title": "Switch X Dropped Packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "packets" }
   ],
   "targets": [
    {
     "expr": "\r\nrate(node_network_transmit_drop_total{device=\"eth0\", instance=\"192.168.3.92:9100\", job=\"node_exporter_cumulus\"}[60s])"
    },
    {
     "expr": "rate(node_network_transmit_drop_total{job=\"$hostname\"}[60s])"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "percentage" }
   ],
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes[10m]) + avg_over_time(node_memory_Cached_bytes[10m]) + avg_over_time(node_memory_Buffers_bytes[10m])) / avg_over_time(node_memory_MemTotal_bytes{job=\"$hostname\"}[10m])))\r"
    }
   ]
  }
 ]
}